### ISSUE TITLE
Error with Nodejs/Restify

### ISSUE THREAD

**Issue by jonatasfreitasv** [DylanPiercey/auto-sni#29]
Hi guys, when i start my server, print this error.

Ubuntu 16 on AWS, i install certbot, and execute server with sudo node ...

I am using ports 8080 http and 8443 https.

[DEBUG le/lib/core.js] registeryAsync err
Error: The CA was unable to validate the file you provisioned.
 - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072617 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072618 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072619 [invalid]
   Could not connect to api.nfebot.com.br
    at handleErr (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:345:17)
    at ensureValidation (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:220:16)
    at Request._callback (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:202:13)
    at Request.self.callback (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
AutoSNI LetsEncrypt Error: { Error: The CA was unable to validate the file you provisioned.
 - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072617 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072618 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072619 [invalid]
   Could not connect to api.nfebot.com.br
    at handleErr (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:345:17)
    at ensureValidation (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:220:16)
    at Request._callback (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:202:13)
    at Request.self.callback (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  cause:
   Error: The CA was unable to validate the file you provisioned.
    - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072617 [pending]
    - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072618 [pending]
    - https://acme-v01.api.letsencrypt.org/acme/challenge/41VhzyM9Exs9wOZwCtk4KdXis544vHkRvXBSkuSXIx8/342072619 [invalid]
      Could not connect to api.nfebot.com.br
       at handleErr (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:345:17)
       at ensureValidation (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:220:16)
       at Request._callback (/home/ubuntu/nf-ebot-api/node_modules/letiny-core/lib/get-certificate.js:202:13)
       at Request.self.callback (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:186:22)
       at emitTwo (events.js:106:13)
       at Request.emit (events.js:191:7)
       at Request.<anonymous> (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:1081:10)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:188:7)
       at IncomingMessage.<anonymous> (/home/ubuntu/nf-ebot-api/node_modules/request/request.js:1001:12)
       at IncomingMessage.g (events.js:292:16)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickDomainCallback (internal/process/next_tick.js:122:9),
  isOperational: true }
Will fall back to self signed certificate.

**Comment by DylanPiercey** [comment]
Can you please post your auto-sni config and OS?
