### ISSUE TITLE
Greenlock updated

### ISSUE THREAD

**Issue by coolaj86** [DylanPiercey/auto-sni#45]
Hello again Dylan,

Just wanted to let you know that greenlock has been updated for Let's Encrypt v2: v2.2

There's a new option `version` that's required since the ACME api doesn't have built-in versioning.

I've tried to clean the docs up quite a bit, so hopefully it's very clear:

https://git.coolaj86.com/coolaj86/greenlock-express.js

**Comment by pyros2097** [comment]
Yep. I'm not able to use the latest version of the package anymore.
This is the error that I get,
```

====================================================================
==                     greenlock.js (v2.2.0+)                     ==
====================================================================

Please specify 'version' option:

        'draft-11' for Let's Encrypt v2 and ACME draft 11
        ('v02' is an alias of 'draft-11'

or

        'v01' for Let's Encrypt v1 (deprecated)

====================================================================
==      this will be required from version v2.3 forward           ==
====================================================================





=== WARNING ===

Due to versioning issues the 'staging' option is deprecated. Please specify the full url and version.

	--acme-url 'https://acme-staging.api.letsencrypt.org/directory' \
	--acme-version 'v01' \



=== WARNING ===

Let's Encrypt v1 is deprecated. Please update to Let's Encrypt v2 (ACME draft 11)

{ Error: Cannot find module 'le-acme-core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

If you require v01 API support (which is deprecated), you must install it:

	npm install le-acme-core

```

**Comment by coolaj86** [comment]
What is it about that error message that is unclear to you and makes you think that it won’t work for you?

I tried to make it clear what action needs to be taken, but the fact that your posting it and saying you can’t use it means that I failed.

It’s saying you need to specify version ‘v01’ or ‘draft-11’, and that you need to npm install le-acme-core I’d you want to use v01, but it’s deprecated, so you should probably upgrade to ‘draft-11’.

What can I change to make that message more clear?

**Comment by coolaj86** [comment]
Oh, you’re saying that auto-sni broke with my latest changes.

All you have to do is the npm install le-acme-core and it’ll work (or the auto-sni package can add the new urls).

I may back part of that change out and republish. I don’t want to break compatibility with modules that aren’t updated yet.

**Comment by pyros2097** [comment]
Ohh.. I just thought this was an issue for auto-sni to be updated to latest upstream changes you made. I want to stick to the latest le version also and don't know how to pass the version attribute as there is no documentation on that in auto-sni. For now I switched to greenlock-express and its working fine.

Also btw the error which is shown above came from running the auto-sni setup.
Funny how the error message for this package contained this,
```
====================================================================
==                     greenlock.js (v2.2.0+)                     ==
====================================================================
```
Which confused this entire thread and also you mentioning the greenlock package in the first comment.
