### ISSUE TITLE
Error in node_modules when on first clean install using code from examples provided.

### ISSUE THREAD

**Issue by casparwylie** [DylanPiercey/auto-sni#6]
**Here is the error produced when trying to run my node server:**

```
html/live_nodejs/node_modules/auto-sni/node_modules/mz/node_modules/any-promise/register.js:61
    throw new Error('Cannot find any-promise implementation nor'+
          ^
Error: Cannot find any-promise implementation nor global.Promise. You must install polypill or call require("any-promise/register") with your preferred implementation, e.g. require("any-promise/register")("bluebird") on application load prior to any require("any-promise").
    at register (/var/www/html/live_nodejs/node_modules/auto-sni/node_modules/mz/node_modules/any-promise/register.js:61:11)
    at Object.<anonymous> (/var/www/html/live_nodejs/node_modules/auto-sni/node_modules/mz/node_modules/any-promise/index.js:1:101)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/live_nodejs/node_modules/auto-sni/node_modules/mz/fs.js:2:15)
    at Module._compile (module.js:456:26)

```

**And here is index.js:**

```
var createServer = require("auto-sin");

var server = createServer({
    email: "test@gmail.com", // Emailed when certificates expire.
    agreeTos: true, // Required for lets encrypt
    debug: true, // Add console messages and uses staging LetsEncrypt server. (Disable in production)
    domains: ["www.test.com", "test.com"], // Optional list of allowed domains (uses pathtoregexp)
    forceSSL: true, // Make this false to disable auto http->https redirects (default true).
    ports: {
        https: 9000 // // Optionally override the default https port.
    }
});

server.listen(9000);
// Server is a "https.createServer" instance.
server.once("listening", function() {
    console.log("We are ready to go.");
});

```.

**Comment by DylanPiercey** [comment]
What version of node are you running? Seems like <0.4.x? This case should be easy to fix, just missing the a promise implementation. I'll get to it later today.

You could get around it temporarily by installing a promise polyfill.

**Comment by DylanPiercey** [comment]
This should be fixed in https://github.com/DylanPiercey/auto-sni/commit/09a0f1a484e5892e57a62075b44061a749a2f561.

Please let me know if this doesn't work for you.

**Comment by SunShinewyf** [comment]
I got this problem too, and then followed your way, it had been solved
